FROM strapi/base

ARG ENVIRONMENT
ARG DATABASE_CLIENT
ARG API_PORT
ARG ADMIN_PORT

WORKDIR /usr/source/app

ENV NODE_ENV $ENVIRONMENT

COPY package*.json ./

RUN npm ci

RUN if [ "$DATABASE_CLIENT" = "postgres" ] ; then npm i --save pg ; fi

COPY . .

RUN npm run build

EXPOSE $API_PORT
EXPOSE $ADMIN_PORT

CMD ["npm", "start"]
